language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
services:
- rabbitmq
install:
- pip install -r ci/requirements.txt
- pip install -r ci/requirements_dev.txt
- pip install --editable .
- pip freeze
env:
- AMQP_VHOST=test PYTEST=py.test
script:
- make test
- coverage
